"""init tables

Revision ID: 6c9a399cff03
Revises: 
Create Date: 2025-11-21 20:19:37.828015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c9a399cff03'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_chat_id')
    )
    op.create_table('polls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_poll_id', sa.Text(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'finished', name='poll_status_type'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.telegram_chat_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_poll_id')
    )
    op.create_table('code_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('poll_id', sa.Text(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.telegram_chat_id'], ),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.telegram_poll_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poll_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('poll_id', sa.Text(), nullable=True),
    sa.Column('option_index', sa.Integer(), nullable=True),
    sa.Column('option_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.telegram_poll_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poll_options')
    op.drop_table('code_lines')
    op.drop_table('polls')
    op.drop_table('chats')
    # ### end Alembic commands ###
